deshaw/versioned-hdf5

versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/hashtable.py, versioned_hdf5/slicetools.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_backend.py, versioned_hdf5/tests/test_hashtable.py, versioned_hdf5/tests/test_versions.py, versioned_hdf5/versions.py
There is now a `chunk_size` parameter to `stage_version`. If not specified, the default chunk size of 2**12 is used.
Fixes #4.
=> Make the chunk_size configurable

versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_backend.py, versioned_hdf5/tests/test_versions.py, versioned_hdf5/versions.py
This also removes the chunk_size parameter from stage_version(). This was the
wrong API, because the chunk size should be per-dataset, not per-version. To
set a chunk size now, set the chunks flag when calling create_dataset(), just
as you would with normal h5py.
@melissawm note the change in the API to set the chunk size here.
=> Allow setting the compression when creating a dataset

versioned_hdf5/api.py, versioned_hdf5/tests/test_api.py
Before this change the current resize logic is incorrectly resizing the
array in data_dict by concatenating with an all zero array of the full
length instead of just the remainder in the last chunk.
This fixes https://github.com/Quansight/versioned-hdf5/issues/35
=> Fix resize computation when last chunk does not align with chunk_size

versioned_hdf5/api.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_versions.py, versioned_hdf5/versions.py
Prior to this, datasets are created in the group of the previous version. But
this actually corrupts the previous version if any new datasets are created.
Instead, we should copy everything over from the previous version. It also
means we shouldn't actually call create_dataset() on the h5py Group object,
but rather fake it so that it goes through our machinery.
This isn't completely fixed yet. There are still some bugs, and we need to
handle groups properly. There are also some tests that need to be fixed, as
well as new tests that need to be written.
This will eventually fix #32 and fix #34.
=> Fix creation of datasets

analysis/generate_data_base.py, generate_data.py, generate_data_no_versions.py
This change makes sure that inserts/deletes only happen on the "most
recent" data. It also changes the logic to only load and write the slice
of the Dataset which is actually impacted which should improve the
performance.
I also refactored the duplicated code between the versioned and regular
test case out into a common base class.
Note that I cannot verify that the versioned tests still succeed since
they no longer work against master, unfortunately.
=> Use powerlaw for insert/delete distribution in generate_data tests

versioned_hdf5/wrappers.py
Fixes #52
CC @ArvidJB 
Before this with 100 transactions, test_mostly_appends_sparse takes 30 seconds. With this branch, it takes 2.7 seconds. I didn't test master with the full 2500 transactions but on this branch it takes 8:40 (@ArvidJB reported it took hours for him on master). I suspect there are still performance gains that can be made. 
Note that for me at least, the generate_data script is broken unless you first merge my branch from #40 into this one.
=> Fix unnecessarily quadratic algorithm to be linear

versioned_hdf5/backend.py, versioned_hdf5/tests/helpers.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_backend.py
h5py by default hard-codes the filename as the virtual data source, meaning if
the file is renamed, it won't be able to find the virtual source, and will
give all 0s (because it masks the error from HDF5). If we instead pass the
undocumented string "." as the file name, it references the current file and
works after renaming.
Fixes #28.
=> Fix reading from hdf5 files that have been moved

versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
Otherwise create_group could create a new object for a group that already has
been made, losing the in-memory datasets and groups that it has on it.
This still needs tests.
Fixes #58.
=> Make InMemoryGroup singletonized per bind

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/versions.py, versioned_hdf5/wrappers.py
We still don't support empty datasets, so the fill value only affects resizes.
Fixes partially #60
=> Add support for fill values

versioned_hdf5/api.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
InMemoryDataset and InMemoryArrayDataset now require the parent InMemoryGroup
to construct, so that they can check the committed property before allowing
writing.
Fixes #5.
=> Disallow writes outside of the context manager

versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
This fixes #69. Storing void data is kind of weirdly supported by h5py
and we seem to use this particular corner case.
=> Support for storing binary data as void

versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
Previously any leading groups on the path to the dataset were stripped
away. This fixes #103.
=> Fix a bug in set_chunks for nested datasets

versioned_hdf5/wrappers.py
h5py has its own custom object dtype objects that are used to support strings.
See issue #111.
Note that this does not yet fix that issue, because there is a problem trying
to create a fillvalue for an object dtype. I'm not sure how to handle that.
=> Keep track of the dtype when creating a dataset

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
We need to manually handle the fillvalue, as there are some bugs in h5py that
prevent it from working. Also, the default fillvalue can show up as None if we
aren't careful, since it can look like an object dtype.
Fixes #111.
=> Add support for variable length string dtypes

versioned_hdf5/api.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
This should fix the memory leak issues (fixes #121). @ArvidJB let me know if you still have memory leaking issues with this PR.
Also fixes trailing slashes in `__contains__` (fixes #122).
=> Garbage collect closed groups

versioned_hdf5/backend.py, versioned_hdf5/hashtable.py, versioned_hdf5/slicetools.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
We need to make sure we have at least one dummy entry in the data_dict so we
can infer the shape.
There is a bug with getting the virtual dataset sources for empty dataset in
h5py, so we have to work around it.
Fixes #98.
=> Fix support for empty datasets

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
Deleting datasets was already supported, but not tested.
This works as long as the dimensionality or dtype does not change between
versions. Changing the dtype would be possible, but would require some work.
Changing the dimensionality would be more difficult.
Fixes #131.
=> Allow deleting groups between versions

versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/versions.py
The previous behavior of requiring an exact timestamp match can be enabled by using vfile.get_version_by_timestamp(timestamp, exact=True).
Fixes #141.
=> Return the closest version before the given timestamp

.travis.yml, setup.py
Version 3 support is being worked on in #148, but will take some time to get
working, and we want to do a release before then.
=> Pin h5py to version 2 for now

versioned_hdf5/backend.py, versioned_hdf5/tests/test_backend.py
Virtual datasets don't have the chunks property, so this is the only way to
access it when reading it from raw HDF5.
Fixes #145.
=> Store the chunks on an attr of the virtual dataset

versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
This used to work because it used to always add trivial chunks, which ended up
maintaining the dtype, but now that it is more efficient, it doesn't do that
any more. The correct behavior is to maintain the dtype, since self.fillvalue
loses that information, basically because of this:
```py
>>> np.array([b''], dtype='S5')[0].dtype
dtype('S')
```
Fixes #161.
=> Fix the str dtype not being maintained from the fillvalue

.authors.yml, .mailmap, AUTHORS.md, asv.conf.json, benchmarks/many_chunks.py, benchmarks/versionedhdf5file.py, docs/changelog.md, rever.xsh, update_benchmarks.sh, versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/hashtable.py, versioned_hdf5/slicetools.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_hashtable.py, versioned_hdf5/versions.py, versioned_hdf5/wrappers.py
The goal here is to improve the performance, particularly in situations where there are many chunks (see https://github.com/deshaw/versioned-hdf5/issues/167). 
This is still a work in progress. 
Some key improvements here:
- Bypass the h5py VirtualSource object and create the layout manually (see the commit message of https://github.com/deshaw/versioned-hdf5/commit/d45a045b2bd7fab0263fd6cc97b4315404400925)
- Allow dataset objects to be promoted from storing a dictionary of chunks to an InMemoryArrayDataset object, which stores a single array. The benefits of referencing the original dataset are lost if the majority of the dataset is modified. Currently this is only done if the entire dataset is modified at once, but it opens open the possibility to do it more generally.
- Directly copy …
=> More performance improvements

versioned_hdf5/tests/conftest.py
This is the issue from https://github.com/deshaw/versioned-hdf5/issues/162.
h5py has a fix, but we won't be able to use it in 2.10.0 unless we manually
backport the patch and custom build h5py. The bug doesn't affect the actual
tests, it just causes them to crash sometimes when the file is closed.
=> Workaround the upstream h5py garbage collection issue

versioned_hdf5/api.py, versioned_hdf5/tests/conftest.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/versions.py
This makes it easier to have a single version group object before the version
is committed, which is important because the object is still writable at that
stage.
=> Disallow accessing vfile[version] before version has been committed

versioned_hdf5/api.py, versioned_hdf5/tests/test_api.py
This addresses some comments that were brought up in issue #162.
=> Better error messages from VersionedHDF5File when the underlying file is closed

setup.py
It looks like PR #148 fixed the incompatibilities and resumed running the CI with h5py 3.x, so hopefully the requirement can be relaxed now.
=> Unpin h5py

.github/workflows/tests.yml, versioned_hdf5/backend.py, versioned_hdf5/replay.py
The sources attribute for VirtualLayout was removed because VirtualLayout now
creates the virtual sources property list directly, so some code that was
manipulating that needed to be rewritten. The upside is that this new
VirtualLayout code should use less memory in cases where a dataset with many
chunks is created.
See https://github.com/h5py/h5py/pull/1905.
=> Fix some issues with h5py 3.3

versioned_hdf5/backend.py, versioned_hdf5/wrappers.py
Fixes #193.
So far this primarily focuses on the read performance, particularly for the case when reading an already committed version. There are still some optimizations that can be made to improve the performance for
- Writing the dataset (especially writing a new dataset).
- Reading the dataset in the case when it is not read-only and some modifications have already been made to it.
- Writing a dataset when the majority, but not the entirety, of the dataset is being overwritten.
I have some ideas how to improve each of these cases, but they will take some work, so we should determine if any of them are not actually that important for our use cases.
=> Improve the performance for small chunks

versioned_hdf5/api.py, versioned_hdf5/tests/conftest.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/versions.py
Also adds some additional type checks on the timestamp in
get_version_by_timestamp() to be consistent with commit_version().
Fixes #190.
=> Fix np.datetime64 handling when the second has 0 fractional part

versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
The direct reading introduced in #194 does not work with virtual datasets, so
we have to fallback to the slower access method. The not supported error
appears to be from HDF5 itself, not h5py.
Fixes #201.
=> Fix reading a dataset with a mask

versioned_hdf5/hashtable.py, versioned_hdf5/tests/test_slicetools.py
Previously it was always filled with 0s to be default_chunk_size aligned, but
this is no longer necessary now that we write to it once at the end. The
chunk_size resizing is still used for the in-memory NumPy array.
This makes the hashtables much smaller on disk for datasets without many
chunks.
This keeps the largest_index attribute for backwards compatibility with hash
tables that were created before this change (which will automatically be
resized down the next time they are written to). It also fixes the
documentation of largest_index.
Fixes #205.
=> Make the hashtable dataset exactly as big as it needs to be

versioned_hdf5/api.py, versioned_hdf5/tests/conftest.py, versioned_hdf5/tests/helpers.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_backend.py, versioned_hdf5/tests/test_hashtable.py
This improves the read performance in these cases. When the file is not in
read-only mode, we still use wrapper classes even for committed groups because
these have the safety checks to prevent accidental writing, which would
corrupt the raw data.
This breaks using mask indices in h5py 2.10 for read-only files, since these
are not supported for virtual datasets and we only support them manually via
the wrappers. h5py 3 does support them, however.
Fixes #217.
=> Don't return wrapper classes when the file is in read-only mode

versioned_hdf5/replay.py, versioned_hdf5/tests/test_replay.py
This requires h5py/h5py#2111 to actually work.
Fixes #234.
=> Fix variable length strings in _recreate_virtual_dataset

.github/workflows/tests.yml, pytest.ini, setup.py, versioned_hdf5/tests/conftest.py, versioned_hdf5/tests/test_api.py
This PR fixes a few issues which interfered with running the tests:
- Sorting slow tests to run at the end of the test run was using a deprecated pytest code path. That's been updated to fix a warning.
- Remove the `test_timestamp_pytz` test, `pytz` was an optional dependency and it isn't really used anymore.
- Removed `--flakes` command line arg; if we want to run a linter I can set it up using pre-commit and github actions to do this in a more robust way
- Added a `.[test]` extra which installs pytest so that the github CI doesn't do this manually
- Drop support for `h5py==2.10`. Supporting this was causing a test to fail before, so this closes #243.
- Removed conda commands from CI, they aren't needed here
- Added CI tests for python 3.10 and 3.11.
=> Fixed a few issues interfering with running tests

.github/workflows/tests.yml, setup.py, versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
This PR fixes versioned-hdf5 to work with the current development version of `h5py`, and removes an instance where we were making an `h5py` internal API call. To ensure we don't break compatibility with future `h5py` versions, I've also added a CI job to run against the development version.
Additionally this PR aligns itself with [NEP29 for python version support](https://numpy.org/neps/nep-0029-deprecation_policy.html), which simplifies the CI.
Closes #246.
=> Fix InMemoryDataset.__getitem__ to work with development version of h5py

versioned_hdf5/replay.py, versioned_hdf5/tests/test_replay.py
This PR modifies how empty datasets are deleted, closing #244.
* As I was debugging, I broke out function definitions from inside `delete_versions` and `_recreate_raw_data` to help separate logic a little  more. I don't think we gain anything by redefining `_walk`, `_get_np_fillvalue`, and `_delete_dataset` during each call, but I can change this back if it's just confusing.
* Added a bunch of type annotations for the functions I touched, it really helped with debugging once I knew what types different objects were.
* When the user deletes one or more versions, and those versions contain one or more datasets which don't exist in the versions being kept (and therefore the raw data needs to be deleted), we now skip recreating the raw data, recalculating hash tables, and recreating the …
=> Correctly handle deletion of empty datasets

versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
This PR logs a message when exiting the `VersionedHDF5File.stage_version` context manager displaying some useful information about the data written. Information is displayed at the `INFO` log level.
This PR closes #166.
Here's a simple example taken from a test:
```python
import logging
import pathlib
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File
logging.basicConfig(level=logging.INFO)
dt = np.dtype('double')
for p in pathlib.Path().glob("*.h5"):
p.unlink()
with h5py.File('foo.h5', 'w') as f:
vf = VersionedHDF5File(f)
with vf.stage_version('0') as sv:
sv.create_dataset('bar', (2, 15220, 2),
chunks=(300, 100, 2),
dtype=dt, data=np.full((2, 15220, 2), 0, dtype=dt))
sv.create_dataset('baz', (1, 10, 2),
chunks=(600, 2, 4),
dtype=dt, data=np.full((1, 10, 2), 0, …
```
=> Add info log showing stats about data upon exiting stage_version context

.github/workflows/pypi_publish.yml
This PR adds a workflow to publish the package to PYPI using [trusted publishing.](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) We'll need to add this workflow as a trusted publisher for the project before the next release.
Partially addresses #258.
=> Add workflow to publish to pypi upon release tag

.github/workflows/docs.yml, .github/workflows/publish_docs.yml, docs/conf.py, rever.xsh, setup.py, versioned_hdf5/replay.py
This PR handles automatic building and deploying of the docs.
- A new workflow was added to ensure doc builds pass on every PR
- A new workflow was added which builds and deploys docs when there's a push to the `master` branch. This workflow makes use of the new github pages action-based deployment mechanism.
- Finally, sphinx refused to build unless I used a string type annotation for `delete_versions`. I think this has something to do with `h5py.File` being a dependency, but I couldn't get sphinx to build if I did anything else. Here's all the things I tried that failed to build:
- Using `sphinx.ext.intersphinx` and setting `intersphinx_mapping` to the `h5py` docs. I verified that the correct object file was being pulled by `sphinx` during the build process, and that the object file …
=> Test docs on PR; deploy docs on push to default branch

.github/workflows/tests.yml, versioned_hdf5/replay.py, versioned_hdf5/tests/conftest.py, versioned_hdf5/tests/test_replay.py
Pasing a non-None fillvalue during vlen dtype datset creation results in a corrupted dataset creation whose access later fails with - 'RuntimeError: Unable to get dataset creation properties'. To avoid this unexpected failure most of the existing code does use None as fillvalue, but in a corner case involving deletion of versions, the creation of the raw dataset with empty data chunks ends up using non-None fillvalue and complains on access after h5 repack.
Changes:
==============
- Fixed the fillvalue being passed,
- Added fixture to return a temp filename, and
- Added test
Fixes #238.
=> Pass None as fill value for vlen raw dataset recreation

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_backend.py
This PR guesses a sensible default chunk size if none is provided, closing #198. Here, we make use of `h5py._hl.filters.guess_chunk` for this purpose. Note this only applies to 1D datasets, with the behavior of scalar and multidimensional datasets unchanged.
The change is quite short, but many of the tests were writing `DEFAULT_CHUNK_SIZE`-sized datasets to files, and then checking that the chunks written matched the `DEFAULT_CHUNK_SIZE`. As a result, many tests needed to be modified to lift this assumption.
=> Guess a sensible default chunk size if none specified

versioned_hdf5/api.py, versioned_hdf5/replay.py, versioned_hdf5/tests/test_replay.py, versioned_hdf5/wrappers.py
This PR avoids writing a `_tmp_raw_data` array in calls to `_recreate_raw_data`, preventing an allocation that in the past could consume lots of memory, causing `delete_versions` to fail. Closes https://github.com/deshaw/versioned-hdf5/issues/273.
NOTE: This is a WIP PR - right now I'm seeing a really weird issue with the tests in `test_replay.py` where calls to `np.testing.assert_equal` are failing on tests which have had deleted versions. I'm guessing this is some issue flushing to disk; creating this PR here for further investigation.
Okay, confirmed that closing and opening the file objects in the offending tests seems to resolve the issue. Will look for a way to flush output to disk to close this out.
---
The intermittent test failures are indeed resolved by calling `gc.collect` at …
=> Delete versions OOM fix

versioned_hdf5/replay.py, versioned_hdf5/tests/test_replay.py
This PR rewrites the `test_delete_versions_speed` to use a mock instead of `linecache` and `sys.settrace`. This avoids us having to change the expected line number every time we make a change to `replay.py`.
I had to redo the math on the execution count here. Closes https://github.com/deshaw/versioned-hdf5/issues/271.
=> Rewrite test_delete_versions_speed to use mocks

versioned_hdf5/versions.py
This PR removes the final remaining `pp` alias from `versions.py`, which previously would interfere with pretty-printing during debugging. Closes https://github.com/deshaw/versioned-hdf5/issues/269.
=> Remove all pp aliases, call posixpath explicitly

.github/workflows/pypi_publish.yml
This PR fixes a pair of instances where a deprecated parameter was being used in the workflow that publishes to PYPI. This will be deprecated soon, so this PR will prevent the job from failing in the future. Closes #268.
=> Fix deprecated CI parameter

versioned_hdf5/backend.py, versioned_hdf5/tests/conftest.py, versioned_hdf5/tests/test_hashtable.py
This PR adds a check when writing data to a file. This check verifies that chunks of data that already exist in the hashtable correspond to arrays that match the data we are trying to write.
This should incur a performance overhead when writing datasets that reuse chunks, but ensures we won't be corrupting hashtables in the future. Closes #294.
Note: Currently I'm seeing a test failure locally with `test_delete_string_dataset` on `master`. The failure happens when trying to open the file after running `h5repack` on the `hdf5` file, with `OSError: Unable to open file (bad object header version number)`. I'm opening this PR to see if CI sees it.
=> Add check of hashed data when writing new data

docs/conf.py, versioned_hdf5/api.py, versioned_hdf5/tests/test_api.py
This PR adds an API for calculating the diff between two versions of a dataset; closes #264.
Tests are provided which check
- The diff between a version and itself is nothing
- The diff between two versions of a dataset gives the expected slices and data, including for nested datasets
An intersphinx mapping was added for numpy as well in order to handle docstrings for this new function.
I wrote a small benchmark to check how fast this implementation was. In the benchmark, I compared calling `get_diff` to iterating over two versions of a dataset and comparing the chunks using `np.assert_equal`. For very small datasets, direct comparison with numpy is fastest. As datasets get larger, directly iterating over the data becomes impractical:
@rahasurana Can you take a look at this?
=> Add diff API

versioned_hdf5/api.py, versioned_hdf5/replay.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_replay.py
This PR optimizes a part of the `_recreate_raw_dataset` that currently can allocate significant memory for datasets with large numbers of versions. I also saw a large speedup in this section of the code post-refactor.
A `VersionedHDF5File.versions` method was added (a `VersionedHDF5` should know what versions it has), which should return the same thing as `versioned_hdf5.versions.all_versions` but be much less verbose and more convenient.
Partially addresses https://github.com/deshaw/versioned-hdf5/issues/298. Deleting datasets can still be costly in terms of memory because the operation requires 
1. Reconstructing the raw dataset, which entails keeping track of the raw chunks that need to be kept
2. Reconstructing the hashtable, which requires loading the inverse of the old hashtable as …
=> Optimize `_recreate_raw_dataset` to use less memory; add versions method

versioned_hdf5/tests/test_versions.py, versioned_hdf5/versions.py
This PR adds a list of forbidden dataset names that are checked when the user tries to commit a new version. If the user tries to save a dataset with one of these names, a `ValueError` is raised.
For this PR, `versions` has been added as a forbidden name, as it conflicts with `/_version_data/versions` leading to a cryptic and unhelpful error message.
=> Check dataset names against blocklist before committing

.pre-commit-config.yaml, docs/performance.rst, docs/performance_filesizes.rst, docs/quickstart.rst
This PR resolves a number of code formatting issues in the documentation:
1. `pygrep-hooks` pre-commit hooks are now enabled
2. Replaced a number of cases where code block literals should be enclosed in double backticks in the documentation
=> Resolve pygrep-hooks issues in documentation

pyproject.toml, versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_backend.py
This PR makes `create_virtual_dataset` correctly handle the case where the raw data is empty, returning an empty virtual dataset.
Closes #314.
- If the raw data for a dataset is empty, the virtual dataset is also empty instead of being shape `(1,)` (??)
- Added tests of both the backend (to see if zero-length raw datasets are correctly handled) and of the API (to cover the reproducer submitted with the original issue)
- Added ANN001 (missing type annotations) to the list of rules to ignore in for test functions. These are either parametrizations or pytest fixtures.
I'm still not entirely sure why it is necessary to close/open the file descriptor between each operation to reproduce this issue, but it must be something to do with flushing writes to the file. @ArvidJB any ideas?
=> Make create_virtual_dataset handle zero-length raw_data correctly

meson.build
This PR adds tests to install as part of the `meson.build` file in order for it to be possible to install the package in editable mode and still be able to run tests.
=> Add tests to the meson.build file so that editable installs can test

versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
This PR makes `InMemoryGroup` reprs more informative, closing #316.
`h5py.Group` reprs don't by default show anything about their data hierarchy. This change makes `InMemoryGroup` reprs show their child objects as part of their repr, making them substantially more useful. For example, in the test written below, `repr(premade_group)` returns:
```
<InMemoryGroup "/group" (3 members)>
<InMemoryArrayDataset "foo": shape (6,), type "<f8">
<InMemoryArrayDataset "bar": shape (6,), type "<f8">
<InMemoryArrayDataset "baz": shape (6,), type "<f8">
```
Later on, we might consider replacing `InMemoryDataset.keys()` and `InMemoryDataset.values()`, and `InMemoryDataset.items()` to return more informative string representations as well.
=> Make InMemoryGroup provide more informative reprs

versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/versions.py
Closes #323.
The logic in `_log_version_diff_stats` is currently not correct since it just compares the new `hashtable` with itself. This ends up always logging that all chunks were reused, which is obviously not correct. Furthermore, the size of the hashtable also does not necessarily correlate with the number of chunks reused for a dataset version.
It is also fairly slow since loading the hashtable is expensive if it drops out of the lru_cache (and unnecessary anyway, as discussed above). The calculations also happen regardless of the logging level, which means that they are mostly wasted anyway.
This change simplifies the logging of version diff stats by doing it directly when the dataset is written and when we can observe the number of added reused/chunks.
=> Faster and correct chunk reuse logging

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_hashtable.py
This PR speeds up reused chunk verification by only constructing an error message if the chunk fails to verify. Here's the benchmark from #322 run on my local machine before the change:
```
_     ._   __/__   _ _  _  _ _/_   Recorded: 16:22:16  Samples:  20605
/_//_/// /_\ / //_// / //_'/ //     Duration: 20.741    CPU time: 22.223
/   _/                      v4.6.2
Program: /home/pdmurray/.pyenv/versions/vhdf/bin/pyinstrument verify_speed.py
20.739 <module>  verify_speed.py:1
├─ 19.710 _GeneratorContextManager.__exit__  contextlib.py:141
│  └─ 19.709 VersionedHDF5File.stage_version  ../../versioned-hdf5/versioned_hdf5/api.py:267
│     └─ 19.699 commit_version  ../../versioned-hdf5/versioned_hdf5/versions.py:71
│        ├─ 19.263 write_dataset …
```
=> Improve speed of reused chunk verification

versioned_hdf5/wrappers.py
By reading the entire current Dataset into a numpy array we can improve the `resize` performance even further. Consider the example from #325:
```
import shutil
import tempfile
import h5py
import numpy as np
from deshaw.constants.dirs import DIR_cluster_tmp
from versioned_hdf5 import VersionedHDF5File
if __name__ == '__main__':
dir = tempfile.mkdtemp(dir=DIR_cluster_tmp())
path = f'{dir}/data.h5'
try:
i = 200
j = 50_000
with h5py.File(path, 'w') as f:
vf = VersionedHDF5File(f)
with vf.stage_version('r0') as sv:
sv.create_dataset('values', data=np.zeros((i, j)), chunks=(10, 100))
for v in range(1, 101):
with vf.stage_version(f'r{v}') as sv:
new_i = i + 1
new_j = j + 500
dataset = sv['values']
dataset.resize((new_i, new_j))
dataset[i:new_i, :j] = 0
dataset[:i, j:new_j] = 0
dataset[i:new_i, …
```
=> resize: read the entire Dataset

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_hashtable.py
In `_verify_chunk_reuse` we need use the shape of the _chunk_ we're writing to read from the raw Dataset instead of the shape of the entire array.
Fixes #333
=> Fix chunk reuse check for multi-dimensional Datasets

.github/workflows/docs.yml, .github/workflows/publish_docs.yml, docs/_templates/versioning.html, docs/conf.py, pyproject.toml
This PR builds and publishes docs for every published tag as well as the `master` branch. Closes #328.
Multiversion docs successfully deployed in my fork: https://github.com/peytondmurray/versioned-hdf5/actions/runs/9422101862/job/25957623096. See https://peytondmurray.github.io/versioned-hdf5 for the actual deployed documentation.
=> Add support for docs version switcher

docs/design.md, pyproject.toml, versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/tests/test_hashtable.py, versioned_hdf5/versions.py
Currently, the verify_chunk_reuse check is relatively slow, see #336. This commit adds an option to disable it by an additional argument to `stage_version(..., verify_chunk_reuse=False)`.
=> Add option to disable verify_chunk_reuse

.github/workflows/publish_docs.yml
This PR forces the master branch to be pulled when building docs for publication; otherwise sphinx-multiversion fails to pull the master branch.
=> Force the master branch to be targeted when building docs to publish

versioned_hdf5/__init__.py
This PR adds a `__version__` dunder back in after it was removed when switching to meson-python. Closes #342.
Tested locally using `pip install -ve .` and using `pip install .`.
=> Add version dunder back in using importlib.metadata

.github/workflows/tests.yml
Internally we are still on numpy version 1.24. After the numpy 2.0 release that means that we were no longer testing against numpy version 1.* but instead were running tests against numpy 2.* twice.
=> Test with numpy 1.24 version now that version 2.* is released

versioned_hdf5/backend.py, versioned_hdf5/tests/test_api.py
This PR fixes an issue with string datasets where reused chunks were not correctly verified.
Previously, chunks that were written to the dataset and then reused contained `bytes` elements, but chunks that were _pending_ a write but being reused (e.g. by some other chunk in the pending write operation) could contain `str` elements, causing problems for the array comparison. With this change, both the chunk that the user is trying to write and the chunk to be reused are coerced to object dtype arrays of bytes before the comparison is completed.
Additionally multidimensional string datasets are now correctly verified as well, closes #339 and closes #338.
=> Fix chunk reuse verification for string dtype arrays

pyproject.toml, versioned_hdf5/hashtable.py, versioned_hdf5/tests/test_hashtable.py, versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
When we read from a multi-dimensional modified Dataset we incur a large overhead from repeatedly computing `as_subindex` operations:
```
In [1]: with h5py.File('data.h5', 'w') as f:
...:     vf = VersionedHDF5File(f)
...:     with vf.stage_version('v0') as sv:
...:         sv.create_dataset('values', data=np.arange(321 * 54321).reshape((321, 54321)), chunks=(10, 100), maxshape=(None, None))
...:
[PYFLYBY] from versioned_hdf5 import VersionedHDF5File
[PYFLYBY] import h5py
[PYFLYBY] import numpy as np
In [3]: %%pyinstrument
...: with h5py.File('data.h5', 'r+') as f:
...:     vf = VersionedHDF5File(f)
...:     with vf.stage_version('v1') as sv:
...:         values = sv['values']
...:         values.resize((432, 65432))
...:         _ = values[:321, :54321]
...:
_     ._   __/__   _ _  _  _ …
```
=> Improve read/writing performance for InMemoryDataset (PyInf#12655)

.github/workflows/publish_docs.yml
Previously, a new build dependency on cython was added, which meant that we added new build time dependencies on hdf5 and mpi. This PR adds these new dependencies to the `publish_docs` CI job so that the docs can be built, fixing it.
=> Add additional non-python build dependencies for publish_docs CI job

.github/workflows/tests.yml, pyproject.toml, pytest.ini
This PR cleans up the pytest config, and adds a bit of crucial debugging information for the test workflow:
1. The hdf5 config is now displayed before each test run starts
2. Automatically use `--import-mode=importlib` in the default pytest `addopts` options, so that we don't have to remember to always run `pytest --import-mode=importlib`.
=> Clean up `pytest` config; make test workflow print `hdf5` config

versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
This PR ensures that `InMemoryGroup` instances close child `InMemoryGroup` instances if they themselves get closed. This means that if a parent group gets committed, any child instance will too. Closes #318.
=> Make `InMemoryDataset` close child instances if self is closed

pyproject.toml, versioned_hdf5/slicetools.pyx
This PR updates the list of typedefs included from `hdf5.h` in `slicetools.pyx` to match what `h5py` does in `h5py/api_types_hdf5.pxd`. I'm not exactly sure why adding these types resolved local testing problems, but there were clues that this was some kind of typing issue - see #352 for context. Closes #352.
=> Explicitly add all hdf5 types to slicetools to fix local tests

.github/workflows/docs.yml, .github/workflows/publish_docs.yml, .github/workflows/tests.yml
This PR makes the workflow first run `apt update` before attempting to installing native dependencies; currently workflows are broken because `libhdf5` fails to install:
```
Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/c/curl/libcurl4-openssl-dev_7.81.0-1ubuntu1.16_amd64.deb  404  Not Found 
```
This PR should resolve this issue.
=> Make the tests workflow update before installing native deps

.github/workflows/pypi_publish.yml, docs/changelog.md
This PR adds cibuildwheel into the `pypi_publish.yml` workflow to allow us to build on all platforms.
The changelog has also been updated in preparation for 1.8.0.
=> Release prep v1.8.0

pyproject.toml, versioned_hdf5/api.py, versioned_hdf5/backend.py
Bulk import sane settings for mypy from another project.
Downstream of this, mypy reports 21 errors, all nontrivial. 
Having a fully green mypy run would take substantially more effort and is out of scope for this PR.
=> Sane mypy settings

versioned_hdf5/wrappers.py
This PR improves exceptions that are raised by `create_dataset`, in many cases to include information about what the offending arguments passed to the function were. The PR also adds type annotations and documentation for `_make_new_dset`.
Closes #331.
=> Improve the exceptions raised by `create_dataset`

versioned_hdf5/tests/test_subchunk_map.py
Rework test_subchunk_map:
- Remove dependency from ndindex. Don't assume that ndindex does the right thing.
- Rework the hypothesis strategy so that it's separate from the test. This is propaedeutic to reuse the same strategy later on in different tests.
- Add use case of scalar indices (it was completely missing!)
- Add use case of slice start, stop, and/or step exceeding array size
- Add use case of index shorter than ndim
- Add use case of chunk size = 1
- Add use case of integer array indices with repeated elements, possibly larger than original array
=> [InMemoryDataset redesign] Overhaul test_subchunk_map

pyproject.toml, versioned_hdf5/meson.build, versioned_hdf5/slicetools.pyx, versioned_hdf5/tests/test_slicetools.py
This is an alternative to #370 after it's been found out that virtual datasets perform very poorly in libhdf5.
Add a function to quickly read potentially thousands of slices from HDF5 into a numpy array, or between numpy arrays. This new function remains dormant for now and will be used in a later PR by a variant of StagedChangesArray from #370.
=> [InMemoryDataset redesign] Read many slices at once with the HDF5 C API

versioned_hdf5/slicetools.pyx
- Closes #356
- Orthogonal to #379
Add H5SClose calls to build_data_dict() to release libhdf5 resources after they've been acquired.
=> Always call H5SClose

.gitignore, meson.build, versioned_hdf5/cytools.pxd, versioned_hdf5/cytools.py, versioned_hdf5/cytools.pyx, versioned_hdf5/meson.build, versioned_hdf5/slicetools.pyx, versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_cytools.py, versioned_hdf5/tests/test_slicetools.py
- Refactor some general purpose utility functions into their own module. This will become more important in later PRs as it turns out it's exceptionally hard to cimport anything from slicetools.pyx.
- Review the definition of hsize_t and align it with libhdf5. See comment in the code for full discussion.
=> Centralized cython tools; redefine hsize_t

versioned_hdf5/meson.build, versioned_hdf5/slicetools.pyx, versioned_hdf5/tests/test_tools.py, versioned_hdf5/tools.py
Part of #386 
Variant of np.asarray(a, dtype=dtype), with two differences:
1. If a is a numpy-like array, don't coerce it to a numpy.ndarray
2. If a has a ABI-compatible dtype, return a view instead of a copy
Works around https://github.com/numpy/numpy/issues/27509
=> [InMemoryDataset redesign] New function asarray()

versioned_hdf5/tests/test_tools.py, versioned_hdf5/tools.py
Two new general purpose functions
=> [InMemoryDataset redesign] ix_with_slices, format_ndindex

versioned_hdf5/slicetools.pyx, versioned_hdf5/tests/test_slicetools.py, versioned_hdf5/wrappers.py
Part of #386 
Rewrite `build_data_dict` to serve the new StagedChangesArray introduced by #386.
This PR adds a new function, which remains dormant side-by-side to `build_data_dict`, and will eventually replace it.
Besides unit tests, I've temporarily rigged running this function every time `build_data_dict` runs (see reverted commit) and never crashed. Definitive proof that this function returns correct results throughout the whole test suite is that #386, which uses it, is green.
`build_data_dict` implements logic for a wealth of weird edge cases, which never come up in any unit tests and made no sense to me since, as far as I understand, they could only possibly be generated if someone manually crafted a virtual dataset and then expected versioned_hdf5 to read it. Detailed discussion …
=> [InMemoryDataset redesign] build_indices_and_offsets

versioned_hdf5/cytools.pxd, versioned_hdf5/cytools.py, versioned_hdf5/meson.build, versioned_hdf5/subchunk_map.pxd, versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_subchunk_map.py, versioned_hdf5/wrappers.py
- Part of #386
Refactor `as_chunk_submap` to be built on top of an abstract class, `IndexChunkMapper`, which is then implemented by one subclass per type of index.
This in and by itself is hardly useful, but it will become necessary when these mapper objects will be used all over the place by #370.
Additionally:
- Move the data type for all indices in the module from PySsize_t to hsize_t, to make them compatible with libhdf5 and `slicetools.pyx::read_many_slices()`. This integration will materialize only in a later PR.
- Sanitize arguments order and naming conventions to make it coherent with later additions
=> [InMemoryDataset redesign] Object-oriented as_subchunk_map

versioned_hdf5/tests/test_subchunk_map.py
Part of #386 
Rework hypothesis strategies in `test_subchunk_map` to allow:
- starting from size 0
- generating multiple indices per shape
Both of these features will be leveraged in a later PR to test the StagedChangesArray.
=> [InMemoryDataset redesign] Tweak hypothesis strategies for indices

versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_subchunk_map.py
Part of #386
Harden error control in user input validation in versioned_hdf5 indices. Improve error messages.
=> [InMemoryDataset redesign] Harden validation in subchunk_map

versioned_hdf5/subchunk_map.pxd, versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_subchunk_map.py
- Part of #386 
- Blocked by and incorporates #388 
- Blocked by and incorporates #373
Add new function `read_many_slices_params_nd()`.
This internally uses a helper function `IndexChunkMapper.read_many_slices_param()`, which duplicates functionality from `IndexChunkMapper.chunk_submap()`and will eventually replace it once `as_subchunk_map()` is no longer used.
=> [InMemoryDataset redesign] read_many_slices_param

versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_subchunk_map.py
- Part of #386
Blocked by and incorporates:
- #388 
- #373 
- #390
Add new class EntireChunksMapper, which reamains dormant until a later PR.
=> [InMemoryDataset redesign] EntireChunksMapper

docs/design.md, versioned_hdf5/replay.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/versions.py, versioned_hdf5/wrappers.py
This PR has been broken down into several stages - read below.
`versioned_hdf5.wrappers.InMemoryDataset` is plagued by slowness caused by the control code, both because the control code itself is very slow and because it calls `h5py.Dataset.__getitem__` on the raw_data independently for every single chunk.
This PR completely replaces the internal implementation of InMemoryDataset by instead performing a fast inner loop of calls to H5DRead, directly to the libhdf5 C library. The control logic - the generation of the index information needed to perform the transfers, which was previously performed by `build_data_dict` and `as_subchunk_map` - has also been completely rewritten and is now much more aggressively cythonized.
This new design introduces a helper class, `StagedChangesArray`, to …
=> Redesign InMemoryDataset data model (libhdf5 direct access)

benchmarks/delete_versions.py, benchmarks/inmemoryarraydataset.py, benchmarks/inmemorydataset.py
These backwards compatibility hacks are for extremely old versions of versioned_hdf5 which should no longer interest anybody.
The current benchmark suite is being run in CI on >=1.7.0.
=> Remove legacy hacks in ASV benchmarks

versioned_hdf5/meson.build, versioned_hdf5/slicetools.pyx, versioned_hdf5/subchunk_map.pxd, versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_subchunk_map.py
Clean up no longer used legacy code after #386
This PR embeds and must be merged after all other PRs in the chain listed in #386.
=> [InMemoryDataset redesign] Legacy engine cleanup

.github/workflows/tests.yml, docs/installation.rst, pyproject.toml, versioned_hdf5/backend.py, versioned_hdf5/replay.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_replay.py
- Increase max tested Python version from 3.11 to 3.13
- Test against pinned old versions of all dependencies
- Set the minimum required versions to the minimum tested versions
- Clean up compatibility with obsolete dependencies
=> Review test matrix; test vs. h5py>=3.8.0

versioned_hdf5/staged_changes.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_staged_changes.py
After the changes in 59028f33b3e93d6c69913117e612c2f1a8129735 we no longer handle numpy integer types in `resize`:
```
In [1]: with h5py.File('/tmp/foo.h5', 'w') as f:
...:     vf = VersionedHDF5File(f)
...:     with vf.stage_version('r0') as sv:
...:         sv.create_dataset('values', data=np.arange(123), chunks=(10,))
...:
[PYFLYBY] from versioned_hdf5 import VersionedHDF5File
[PYFLYBY] import h5py
[PYFLYBY] import numpy as np
In [2]: with h5py.File('/tmp/foo.h5', 'r+') as f:
...:     vf = VersionedHDF5File(f)
...:     with vf.stage_version('r1') as sv:
...:         old_length = sv['values'].size
...:         new_length = old_length - 17
...:         sv['values'].resize((new_length,))
...:
---------------------------------------------------------------------------
TypeError …
```
=> Handle numpy ints in resize operations

versioned_hdf5/staged_changes.py, versioned_hdf5/tests/test_staged_changes.py
minor performance boost on datasets with huge amounts of chunks
=> Speed up chunks geometry maths on resize() to shrink

docs/conf.py
This PR fixes an issue where more recent versions of the documentation were not being built by `sphinx-multiversion`. This is because only tags of the form `1.7.0` were allowed, while `v1.8.0` was not. This restriction has been removed.
=> [BUG] Fix sphinx config that prevents certain tags from being built

versioned_hdf5/replay.py
Fixes #419.
This PR fixes an issue where empty datasets were not being detected correctly, which manifested as a bug when deleting empty datasets. Usually if the user deletes a version of empty dataset, the raw data is not modified because empty datasets don't point to any raw data. If the dataset to be deleted was not empty, this triggers a recreation of the hash table, raw data, and virtual datasets; if the dataset to be deleted was not virtual, we'd skip all of that.
To determine whether a dataset was empty, previously we were checking whether the dataset was virtual, because with previous versions of h5py empty datasets were never allowed to be virtual. With the latest version of h5py empty datasets can now be virtual, meaning our detection logic fails. As a result the raw data, hash …
=> [BUG] Change empty dataset detection to work with h5py dev version

pyproject.toml, versioned_hdf5/tests/test_api.py, versioned_hdf5/wrappers.py
Fix crash with a DTypeLike parameter to `create_dataset`, e.g. `dtype="i4"` instead of `dtype=np.int32`.
=> Accept DTypeLike in `dtype=` parameter in `create_dataset`

versioned_hdf5/backend.py, versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
Fix bugs where `InMemoryArrayDataset.__getitem__` and `__array__` would return the wrong dtype.
Speed up `create_dataset` with list data and explicit dtype, by avoiding a double conversion e.g. list -> np.int64 -> np.int16 (or whatever is the desired dtype).
=> Fix InMemoryArrayDataset dtype

versioned_hdf5/meson.build, versioned_hdf5/slicetools.pyx, versioned_hdf5/staged_changes.py, versioned_hdf5/subchunk_map.py, versioned_hdf5/tests/test_slicetools.py, versioned_hdf5/tests/test_staged_changes.py, versioned_hdf5/tests/test_tools.py, versioned_hdf5/tests/test_typing.py, versioned_hdf5/tools.py, versioned_hdf5/typing_.py
Tighten the API surface that a "numpy-like" object must expose in order to be accepted as as a StagedChangesArray base slab. This PR allows h5py `AsTypeView` objects to qualify, and is propaedeutic to implementing NpyStrings datasets (https://github.com/h5py/h5py/pull/2557)
=> StagedChangesArray to accept AsTypeView as base slab

versioned_hdf5/replay.py, versioned_hdf5/staged_changes.py, versioned_hdf5/tests/test_api.py, versioned_hdf5/tests/test_replay.py, versioned_hdf5/tests/test_slicetools.py, versioned_hdf5/tests/test_wrappers.py, versioned_hdf5/wrappers.py
- Fixed bug where setting `fillvalue=0` would retain the previous fillvalue
- Speed up when the `fillvalue` doesn't change
- Added test for changing  `dtype` on sparse datasets
- Fixed bug when changing `dtype` and `fillvalue` at the same time, which could cause the new `fillvalue` to be transitorily cast to the old `dtype` and overflow, underflow, or lose definition
- Removed an _astonishing_ amount of dead or useless code
- Simplified code flow
- Removed "lazy" logic in `InMemoryArrayDataset` dtype. It was offering zero performance benefits compared to just eagerly converting input arrays from the users, while being ripe with complexity and bugs.
- Fixed bug that would lead to overflow/underflow/loss of definition after calling `__setitem__` on the initial version of a dataset, caused …
=> wrappers spring cleaning

benchmarks/common.py, benchmarks/hashtable.py, benchmarks/strings.py
- Blocked by and incorporates https://github.com/deshaw/versioned-hdf5/pull/442.
- #427 enables dtype="T" and fixes `astype` test failures
See only final commit.
**tip:** you can pip-install a different branch (#427), switch back to this branch, and run `asv run --python=same --quick`
=> NpyStrings benchmarks

CONTRIBUTING.md
Use the deshaw org's default CONTRIBUTING.md community health file, located at https://github.com/deshaw/.github/blob/80087ec4b1eb10ad397978632dacc55c608973bf/.github/CONTRIBUTING.md
CC @mlucool
=> Use org-wide default CONTRIBUTING.md

.github/workflows/pypi_publish.yml, docs/releasing.md
A PR can now opt in to have the wheels CI run without waiting for a release. Just add the `wheels` label and reopen the PR.
=> Build wheels in selected PRs

tests/test_wrappers.py, versioned_hdf5/wrappers.py
- Fix bug where the `.compression` and `.compression_opts` properties of staged datasets would incorrectly return None
- Fix bug where passing a path to `create_dataset` would silently disregard the `compression` and `compression_opts` parameters.
e.g. this would work as intended:
```python
with vf.stage_version("r1") as v:
g = v.create_group("a/b")
ds = g.create_dataset("c", compression="gzip")
```
while this would disregard the compression parameter:
```python
with vf.stage_version("r1") as v:
ds = v.create_dataset("a/b/c", compression="gzip")
```
=> Fix bugs around compression parameters and properties

.pre-commit-config.yaml, versioned_hdf5/replay.py, versioned_hdf5/wrappers.py
Refactor `wrappers._groups` as a ClassVar of InMemoryGroup, following the typical pattern for instance trackers.
=> nit: wrappers._groups as ClassVar

tests/test_api.py, tests/test_backend.py, tests/test_replay.py, tests/test_versions.py, tests/test_wrappers.py, versioned_hdf5/api.py, versioned_hdf5/backend.py, versioned_hdf5/replay.py, versioned_hdf5/typing_.py, versioned_hdf5/versions.py, versioned_hdf5/wrappers.py
- Closes https://github.com/deshaw/versioned-hdf5/issues/449
- Rework the implementation of filters
- Add `shuffle`, `fletcher32`, and `scaleoffset` parameters to `create_dataset` and `modify_metadata`
- Fix bug where `modify_metadata` would revert `compression` and `compression_opts` to their default value when they are not explicitly listed. For example, `modify_metadata(ds, fillvalue=123)` would decompress a dataset! You now have to explicitly pass `modify_metadata(ds, compression=None)`.
- `.compression` and `.compression_opts`  properties now return the numerical IDs for custom compression filters (e.g. Blosc, Blosc2) in staged datasets. Note that this is unlike `h5py.Dataset.compression`, which incorrectly returns None.
=> Filters overhaul; add shuffle, fletcher32, scaleoffset
