deshaw/versioned-hdf5

versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py

- It doesn't yet support resizing datasets that aren't multiples of the
chunk size.
- It still needs tests.
Fixes #16.

support for resizing datasets

---

versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py

Hoping that pushing the branch up this repo fixes the Travis thing.

Fix reading a dataset from within the context manager

---

versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py

Fix an issue with resizing an array that is smaller than a chunk size

---

generate_data.py
utils/__init__.py

(which is how we actually use this in practice).
I renamed the previous dense example by appending "_old".
Note that this is not currently supported in VersionedHdf5 so I am just
writing to a regular HDF5 file.

Add an example for writing two dimensional dense data

---

versioned_hdf5/backend.py
versioned_hdf5/tests/test_api.py
versioned_hdf5/tests/test_wrappers.py
versioned_hdf5/versions.py
versioned_hdf5/wrappers.py

This is used when the dataset is created from an array. That way, we don't
have to create a fake Dataset on the file so that we can use InMemoryDataset.

Add InMemoryArrayDataset

---

versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py
versioned_hdf5/tests/test_versions.py
versioned_hdf5/versions.py

Previously it only did this if the context manager exit code raised an
exception.

Delete the version if the context manager body raises an exception

---

.travis.yml
setup.py
versioned_hdf5/backend.py
versioned_hdf5/hashtable.py
versioned_hdf5/slicetools.py
versioned_hdf5/tests/test_slicetools.py
versioned_hdf5/wrappers.py

The equivalent of split_slice is not yet implemented in ndindex, so that remains here for now.

Fix existing code to use ndindex

---

versioned_hdf5/tests/test_api.py

Add a test for assigning a list

---

versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py
versioned_hdf5/versions.py
versioned_hdf5/wrappers.py

This also fixes some issues with nested groups that were behaving incorrectly.
Fixes #66
Fixes #65

Implement InMemoryGroup.__contains__

---

README.md

D. E. Shaw logo used under these terms: https://www.deshaw.com/tmug

Update README with History and Licence

---

README.md
analysis/Performance_tests.ipynb
analysis/Test_IO_Performance.ipynb
docs/conf.py
setup.py

I left the author metadata in places like the LICENSE as "Quansight".

Replace references to Quansight/versioned-hdf5 to deshaw/versioned-hdf5

---

docs/quickstart.rst
versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py

Please let me know if there's a better approach.
Closes #45

Adds close method to VersionedHDF5File objects. Updates docs.

---

docs/quickstart.rst
versioned_hdf5/api.py
versioned_hdf5/tests/test_api.py
versioned_hdf5/tests/test_versions.py
versioned_hdf5/versions.py

I'm not sure the attributes is the right place to store the timestamps, let me know if you think there's a better choice.
Closes #9

Adds timestamps as attributes of version groups.

---

versioned_hdf5/tests/test_wrappers.py
versioned_hdf5/wrappers.py

Add a size attribute to InMemoryArrayDataset

---

.authors.yml
analysis/performance_tests.py
rever.xsh

Fixes rever issues before release.

Rever check

---

docs/CHANGELOG.md
docs/conf.py
docs/index.rst
docs/installation.rst
docs/performance.rst
docs/performance_filesizes.rst
docs/performance_io.rst
docs/usage.rst

Also fixes some small docs issues (Installation instructions and typos).

Move performance docs 

---

pytest.ini
versioned_hdf5/tests/conftest.py
versioned_hdf5/tests/helpers.py
versioned_hdf5/tests/test_api.py
versioned_hdf5/tests/test_backend.py
versioned_hdf5/tests/test_hashtable.py
versioned_hdf5/tests/test_slicetools.py
versioned_hdf5/tests/test_versions.py
versioned_hdf5/tests/test_wrappers.py
versioned_hdf5/wrappers.py

Including some configs to make fixtures more reusable.
Fixes #88

Added fixtures and temporary dirs for tests.

---

versioned_hdf5/tests/test_api.py
versioned_hdf5/wrappers.py

This matches the h5py behavior.

Fix automatic creation of groups on setitem

---

versioned_hdf5/tests/test_api.py
versioned_hdf5/wrappers.py

Make sure scalar indices give scalar objects

---

versioned_hdf5/api.py
versioned_hdf5/backend.py
versioned_hdf5/slicetools.py
versioned_hdf5/tests/test_api.py
versioned_hdf5/versions.py
versioned_hdf5/wrappers.py

#63 was merged prematurely, so this continues that work.

Continuing work on sparse datasets

---

.authors.yml
docs/changelog.md
rever.xsh

Fixes https://github.com/deshaw/versioned-hdf5/issues/149

1.2 release

---

versioned_hdf5/tests/test_api.py
versioned_hdf5/wrappers.py

Maintain attrs in DatasetWrapper

---

docs/changelog.md

1.2.5 release

---

versioned_hdf5/tests/test_api.py
versioned_hdf5/wrappers.py

Store the chunks directly on InMemoryArrayDataset and make sure it is maintained in DatasetWrapper

---

versioned_hdf5/hashtable.py

This was done by avoiding some unnecessary pre-computation that was done in the hashtable object. 
Fixes #187.
Here is a graph of the difference for the script given in the issue. 
If the performance is still too low I can look into other improvements that can be made here.

Improve performance in the case of many versions

---

docs/changelog.md
docs/index.rst
docs/releasing.md
versioned_hdf5/wrappers.py

@ArvidJB I've added documentation on how to make a release. You may want to look it over and see if it looks OK.

1.3.3 release

---

versioned_hdf5/replay.py
versioned_hdf5/tests/test_replay.py

Fix delete_versions() with groups

---

versioned_hdf5/replay.py
versioned_hdf5/tests/test_replay.py

Set current_version in delete_versions

---

versioned_hdf5/replay.py
versioned_hdf5/tests/test_replay.py

Properly handle datasets that are fillvalue-only in delete_versions

---

docs/changelog.md
rever.xsh
versioned_hdf5/replay.py
versioned_hdf5/tests/test_replay.py

Fix the prev_versions in delete_versions

---

docs/changelog.md

This PR adds release notes for v1.4.0.

Add 1.4.0 release notes

---

docs/changelog.md

This PR adds release notes for v1.4.1.

Add 1.4.1 release notes

---

docs/changelog.md

This PR adds release notes for 1.4.2.

Add 1.4.2 release notes

---

versioned_hdf5/replay.py
versioned_hdf5/tests/test_replay.py

This PR guards against exceptions raised when recreating the raw data during a call to `delete_versions`. This step allocates a potentially large numpy array, which may cause an OOM error. In this case, the `_tmp_raw_data` is deleted before the exception is raised.
An additional check is made to remove any existing `_tmp_raw_data` datasets before trying to reconstruct the raw data.
Partially addresses #273.

Guard against exceptions when reconstructing raw data in `delete_versions`

---

docs/changelog.md

This PR adds release notes for 1.4.3.

Add 1.4.3 release notes

---

docs/changelog.md

This PR adds release notes for 1.5.0.

Add 1.5.0 release notes

---

docs/changelog.md

This PR adds release notes for 1.6.0.

Add 1.6.0 release notes

---

docs/changelog.md

This PR adds a few minor changes I missed in the first 1.6.0 release notes.

Fixed 1.6.0 release notes

---

versioned_hdf5/tests/test_api.py
versioned_hdf5/wrappers.py

This PR optimizes `InMemoryDataset.resize` to avoid quadratic performance with the number of chunks in `InMemoryDataset.data_dict`; closes #325.
When calling `resize()`, any chunk of the dataset which is at the edge of the new dataset's shape needs to be read, and these chunks then need to be written to the raw dataset. In the process of reading the data for each edge-chunk in `Dataset.data_dict`, each call to `InMemoryDataset.__getitem__` would execute `InMemoryDatasetID.can_read_direct`, which itself iterates through every item in `Dataset.data_dict`, leading to very slow performance for certain datasets with large `data_dict`.
This PR introduces a new `Dataset.get_index` method which takes a `can_read_direct` parameter, allowing `InMemoryDataset.resize` to call …

Optimize `InMemoryDataset.resize` to avoid quadratic performance

---

docs/changelog.md

This PR adds release notes for 1.7.0.

Add 1.7.0 release notes

---

versioned_hdf5/slicetools.pyx
versioned_hdf5/wrappers.py

Also add some more comments and simplify `build_data_dict` by moving the non-virtual case out.

Fix H5S_sel_type enum declaration

---

docs/design.md

Assorted minor tweaks to the design document

Nitpicks in design doc

---

versioned_hdf5/slicetools.pyx

Skip health checks in build_data_dict

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
versioned_hdf5/backend.py
versioned_hdf5/subchunk_map.py
versioned_hdf5/wrappers.py

The pre-commit CI job has recently started misbehaving due to the upgrade of ubuntu-latest from 22.04 to 24.04.
e.g. https://github.com/deshaw/versioned-hdf5/actions/runs/11348180310/job/31561463192?pr=380

Repair pre-commit CI

---

versioned_hdf5/hashtable.py

Remove an unnecessary deep-copy of numpy arrays when they are passed to the hashing functions. On a dataset of 3 GiB total and 40_000 chunks, this shaves \~0.5s (\~5%) off the commit time.
Additionally, fix a bug where object arrays would generate a different hash on 32-bit platforms vs. 64-bit platforms, as well as on big-endian platforms (PowerPC) vs. little-endian platforms (x86/ARM).

Don't deep-copy when hashing

---

.gitignore
docs/index.rst
docs/staged_changes.rst
versioned_hdf5/meson.build
versioned_hdf5/staged_changes.py
versioned_hdf5/tests/test_staged_changes.py
versioned_hdf5/wrappers.py

Part of #386
New class StagedChangesArray, which is the new engine underlying the InMemoryDataset. This class is not yet used and will remain dormant until the next PR #386 hot-swaps the engine.

[InMemoryDataset redesign] StagedChangesArray

---

versioned_hdf5/subchunk_map.py
versioned_hdf5/tests/test_subchunk_map.py

- Add support for ... in both `__getitem__` and `__setitem__` indices
- Add test coverage for use case of an ndindex made of one or more scalar indices plus a fancy index, e.g. `[0, [0]]`

Add support for ellipsis in indices

---

versioned_hdf5/staged_changes.py
versioned_hdf5/tests/test_replay.py
versioned_hdf5/tests/test_staged_changes.py

Fix regression: shrinking corrupts the hash table

---

.github/workflows/tests.yml
.pre-commit-config.yaml
pyproject.toml
tests/conftest.py
tests/test_api.py
tests/test_backend.py
tests/test_replay.py
tests/test_staged_changes.py
tests/test_subchunk_map.py
versioned_hdf5/subchunk_map.py

Follow-up to #433. Some more tweaks. Number of ruff errors going very slowly down.

Another partial linters pass

---

tests/test_api.py
versioned_hdf5/wrappers.py

- Fix crash and add test coverage for `InMemorySparseDataset.resize()`
- Add test coverage for `*Dataset.resize(..., axis=n)`
- Ensure that edge cases (np.int64, ndarray[int], list, etc.) are properly handled

Test coverage for `resize()`; fix crash
